import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/provider/jotai-provider";
import { moulpali } from "@/app/fonts";
import {
  ModalPayCard,
  ModalPayCash,
  ModalPurchase,
  ModalSell,
  ModalTrade,
} from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={moulpali.className}>
        <Providers>
          {children}
          <ModalPayCard />
          <ModalPayCash />
          <ModalPurchase />
          <ModalTrade />
          <ModalSell />
        </Providers>
      </body>
    </html>
  );
}
